jobs:
- job: everything
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/pascalicoverage-ubuntu-jdk8:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./create-directory-structure.sh
    displayName: create-directory-structure.sh
# TODO: clone Randoop, run ./gradlew assemble, then run replace-randoop.sh
